OAK-1617 - Automatically convert "or" queries to "union" for SQL-2
- EquiJoinConditionImpl now implements copyOf()
- cleared regression in testJoinWithOR

# TODO

- [oak-jcr] testJoinWithOR5(org.apache.jackrabbit.core.query.JoinTest):
Wrong hit count. expected:<2> but was:<0>
- [oak-jcr] testJoinWithOR2(org.apache.jackrabbit.core.query.JoinTest)
- [oak-jcr] or[0](org.apache.jackrabbit.oak.jcr.query.QueryTest)
- restore commented tests in QueryJcrTest
- test more complex queries by forcing unions.
- perform the actual optimisation
- prepare all queries and get cheapest
- check flag for forcing optimised version
- execute the cheapest query
- remove the init() hack